package com.mycompany.quedeahuevo2;

import java.awt.Dimension;
import javax.swing.JDesktopPane;


public class Menu extends javax.swing.JFrame {
    
    public static JDesktopPane DesktopPane_menu;
            

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        
        this.setLayout(null);
        DesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        this.DesktopPane_menu.setBounds(0, 0,ancho, (alto -110));
        this.add(DesktopPane_menu);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuNuevoUs = new javax.swing.JMenuItem();
        menuBorrarUsuario = new javax.swing.JMenuItem();
        menuListaUsuario = new javax.swing.JMenuItem();
        menuActualizarUsu = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenu();
        menuNuevoProducto = new javax.swing.JMenuItem();
        menuListaProductos = new javax.swing.JMenuItem();
        menuActualizarProducto = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuNuevoCliente = new javax.swing.JMenuItem();
        menuListaClientes = new javax.swing.JMenuItem();
        menuCategorias = new javax.swing.JMenu();
        menuNuevaCategoria = new javax.swing.JMenuItem();
        menuListaCategorias = new javax.swing.JMenuItem();
        menuFacturas = new javax.swing.JMenu();
        menuNuevaVentas = new javax.swing.JMenuItem();
        menuListaVentas = new javax.swing.JMenuItem();
        menuHistorial = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        CerrarSesión = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuUsuario.setText("Usuario");
        menuUsuario.setPreferredSize(new java.awt.Dimension(150, 50));

        menuNuevoUs.setText("Nuevo Usuario");
        menuUsuario.add(menuNuevoUs);

        menuBorrarUsuario.setText("Borrar Usuario");
        menuBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBorrarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuBorrarUsuario);

        menuListaUsuario.setText("Listade Usuario");
        menuUsuario.add(menuListaUsuario);

        menuActualizarUsu.setText("Actualizar Usuario");
        menuUsuario.add(menuActualizarUsu);

        jMenuBar1.add(menuUsuario);

        menuProductos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuProductos.setText("Producto");
        menuProductos.setPreferredSize(new java.awt.Dimension(150, 50));

        menuNuevoProducto.setText("Nuevo Producto");
        menuNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoProductoActionPerformed(evt);
            }
        });
        menuProductos.add(menuNuevoProducto);

        menuListaProductos.setText("Lista de Productos");
        menuProductos.add(menuListaProductos);

        menuActualizarProducto.setText("Actualizar Producto");
        menuProductos.add(menuActualizarProducto);

        jMenuBar1.add(menuProductos);

        menuClientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuClientes.setText("Clientes");
        menuClientes.setPreferredSize(new java.awt.Dimension(150, 50));

        menuNuevoCliente.setText("Nuevo Cliente");
        menuClientes.add(menuNuevoCliente);

        menuListaClientes.setText("Lista de Clientes");
        menuClientes.add(menuListaClientes);

        jMenuBar1.add(menuClientes);

        menuCategorias.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuCategorias.setText("Categoria");
        menuCategorias.setPreferredSize(new java.awt.Dimension(150, 50));

        menuNuevaCategoria.setText("Nueva Categoria");
        menuNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevaCategoriaActionPerformed(evt);
            }
        });
        menuCategorias.add(menuNuevaCategoria);

        menuListaCategorias.setText("Lista De Categorias");
        menuListaCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListaCategoriasActionPerformed(evt);
            }
        });
        menuCategorias.add(menuListaCategorias);

        jMenuBar1.add(menuCategorias);

        menuFacturas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuFacturas.setText("Factura");
        menuFacturas.setPreferredSize(new java.awt.Dimension(150, 50));

        menuNuevaVentas.setText("Nueva Venta");
        menuFacturas.add(menuNuevaVentas);

        menuListaVentas.setText("Lista de Ventas");
        menuFacturas.add(menuListaVentas);

        jMenuBar1.add(menuFacturas);

        menuHistorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuHistorial.setText("Historial");
        menuHistorial.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem14.setText("Ver");
        menuHistorial.add(jMenuItem14);

        jMenuBar1.add(menuHistorial);

        CerrarSesión.setText("Cerrar Sesión");
        CerrarSesión.setPreferredSize(new java.awt.Dimension(150, 50));
        jMenuBar1.add(CerrarSesión);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBorrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBorrarUsuarioActionPerformed

    private void menuNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevaCategoriaActionPerformed
        IntCategoria intCategoria = new IntCategoria();
        DesktopPane_menu.add(intCategoria);
        intCategoria.setVisible(true);   
    }//GEN-LAST:event_menuNuevaCategoriaActionPerformed

    private void menuNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNuevoProductoActionPerformed

    private void menuListaCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListaCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuListaCategoriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CerrarSesión;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem menuActualizarProducto;
    private javax.swing.JMenuItem menuActualizarUsu;
    private javax.swing.JMenuItem menuBorrarUsuario;
    private javax.swing.JMenu menuCategorias;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuFacturas;
    private javax.swing.JMenu menuHistorial;
    private javax.swing.JMenuItem menuListaCategorias;
    private javax.swing.JMenuItem menuListaClientes;
    private javax.swing.JMenuItem menuListaProductos;
    private javax.swing.JMenuItem menuListaUsuario;
    private javax.swing.JMenuItem menuListaVentas;
    private javax.swing.JMenuItem menuNuevaCategoria;
    private javax.swing.JMenuItem menuNuevaVentas;
    private javax.swing.JMenuItem menuNuevoCliente;
    private javax.swing.JMenuItem menuNuevoProducto;
    private javax.swing.JMenuItem menuNuevoUs;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
